format_version: 10
pipelines:
  HelloDocker:
    group: helloGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-b9b58f0:
        git: https://github.com/aswroma3/gocd.git
        shallow_clone: false
        auto_update: true
        branch: main
      HelloJavaBuild:
        ignore_for_scheduling: false
        pipeline: HelloJavaBuild
        stage: GradleBuild
      HelloApiTest:
        ignore_for_scheduling: false
        pipeline: HelloApiTest
        stage: ApiTest
    stages:
    - DockerBuild:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build:
            timeout: 0
            tasks:
            - fetch:
                is_file: false
                source: hello-libs
                destination: hello-docker/tmp
                pipeline: HelloJavaBuild
                stage: GradleBuild
                job: Build
                artifact_origin: gocd
                run_if: passed
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    cd hello-docker
                    mv tmp/hello-libs/hello.jar hello.jar
                    ls -la
                    docker build --rm -t hello-123 .
                    docker image ls
                  shtype: bash
                run_if: passed
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    cd hello-api-test
                    ls -la
                    docker image ls
                    docker run -d -p 8081:8080 --name my-hello-123 hello-123
                    chmod a+x smoke-test.sh
                    ./smoke-test.sh http://localhost:8081/actuator/health 180
                    HELLO_API_PORT=8081 gradle test
                    sleep 5\ndocker ps -a
                    docker stop my-hello-123
                    docker rm my-hello-123
                    docker ps -a
                  shtype: bash
                run_if: passed
